spring:
  # 配置数据库连接池
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-app?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  ### 配置Redis
  redis:
    database: 0
    host: 10.0.0.32
    port: 6379
    password: 1470634109

#OSS服务对应信息
file:
  oss:
    accessKeyId:
    endpoint:
    accessKeySecret:
    bucketName:
    accessPath:   #oss文件内网地址前缀